language: php
sudo: false
php:
  - "5.5"
  - "5.6"
  - "7.0"
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install --no-interaction --prefer-dist -d ${TRAVIS_BUILD_DIR}
script:
  - bin/phpcs --standard=PSR2 src
